:Author: ssr_197
:Email: saurabh50197@gmail.com
:Date: 17/10/2017
:Revision: version#
:License: Public Domain

= Project: {Intelligent Flammable Gas Detector using arduino uno R3}

Describe your project

== Step 1: Installation

1. Connect your arduion with usb port to transfer the file.
2. Download the Arduino ide, go to editor and copy paste this file.
3. Edit this code as you like.
4. And save it.


== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch


== Step 3: Load the code

Upload the code contained in this sketch on to your board.

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released as open source.

=== Contributing
To contribute to this project please contact saurabh kumar at ssr_197@yahoo.com

=== BOM
The expected cost of this project is Rs 1050 (Indian National Rupees).
Please note that price may vary from country to country as well as year. This project was made in 2017.

|===
| ID | Part name      | Part number | Quantity

| R1 | 10k Resistor   |     Null    | 2
| L1 | 1K Resistor    |     Null    | 2
| A1 | Arduino UNO    |     Null    | 1
| R1 | Buzzer         |     Null    | 1
| L1 | MQ-5 sensor    |     Null    | 1
| A1 |Connecting wire |     Null    | 50

|===
